version: "3.8"

services:
  target-app:
    image: indosambhav/dist-monitored-app:latest
    ports:
      - "3000:5000"
    container_name: dist-monitored-app
    networks:
      - target-network

networks:
  target-network:
    driver: bridge
